### PR TITLE
Add support for WordPress

### PR DESCRIPTION
**Pull request by tampe125**
This pull request adds support for WordPress (site creation and extension linking).

PLEASE NOTE: Currently all sites will be created under *.vagrant54.up. Since we have to store the full address inside WordPress, I played safe and installed it under PHP 5.4 host.
In the future we should find a way to do proper testing vs different PHP versions.

### CODE REVIEW

**Comment by nikosdion** [comment]
I suggest that we install the WP sites under `*.vagrant.up` and later use .htaccess directives to select the correct PHP version. Since it's FastCGI we can do that in .htaccess.

Moreover, we can always set up  handlers with SetHandler and Action which allow us to use AddHandler in .htaccess to easily switch to different PHP versions, see http://linuxplayer.org/2011/05/intall-multiple-version-of-php-on-one-server

**Comment by nikosdion** [comment]
Ping me or request a review when this is fixed.

**Comment by tampe125** [comment]
WordPress sites are now on created on `*.vagrant.up` domain. Default version is PHP 5.4, changed using .htaccess directives

**Comment by tampe125** [comment]
@nikosdion cant' find a button to tell GitHub to ping you since I made the suggested changes, so we're going in the old way.

**Pull request merged**
